// <auto-generated />
using System;
using Guard.Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Guard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260922093211_Mig15")]
    partial class Mig15
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Guard.Core.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Guard.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonalId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PersonalId")
                        .IsUnique()
                        .HasFilter("\"PersonalId\" IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Guard.Core.Entities.Classifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Уникальный идентификатор записи классификатора");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassifierName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Наименование группы классификатора");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasComment("Код значения внутри конкретного классификатора");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Флаг актуальности записи");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Тип классификатора (числовой код)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Дата и время последнего обновления записи (UTC)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Отображаемое значение элемента");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.ToTable("Classifiers", null, t =>
                        {
                            t.HasComment("Универсальный справочник классификаторов системы");
                        });
                });

            modelBuilder.Entity("Guard.Core.Entities.IpAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("IP-адрес или CIDR-нотация");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Человекочитаемое название");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("IpAddresses", null, t =>
                        {
                            t.HasComment("Справочник IP-адресов и CIDR-подсетей системы Guard. Центральный каталог всех известных IP-адресов и подсетей, которые могут быть назначены пользователям, подразделениям и другим сущностям.");
                        });
                });

            modelBuilder.Entity("Guard.Core.Entities.OrganType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор типа органа");

                    b.Property<int>("ClassifierType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(906)
                        .HasComment("Тип классификатора (906)");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasComment("Код элемента классификатора");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Наименование типа органа");

                    b.HasKey("Id");

                    b.HasIndex("ClassifierType", "Code");

                    b.HasIndex("Id", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_OrganTypes_Id_Code");

                    b.ToTable("OrganTypes", null, t =>
                        {
                            t.HasComment("Справочник типов органов");
                        });
                });

            modelBuilder.Entity("Guard.Core.Entities.Personal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Уникальный идентификатор записи (UUIDv7)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasComment("Идентификатор пользователя (string), создавшего запись. Ссылается на AspNetUsers.Id");

                    b.Property<int?>("EnlistmentYear")
                        .HasColumnType("integer")
                        .HasComment("Год принятия на службу");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Имя");

                    b.Property<string>("FirstNameGen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Имя в родительном падеже");

                    b.Property<string>("FullName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasComment("Фамилия и инициалы");

                    b.Property<DateTime>("InsertedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'")
                        .HasComment("Дата и время создания записи (UTC)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время последнего изменения записи (UTC)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Фамилия");

                    b.Property<string>("LastNameGen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Фамилия в родительном падеже");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Отчество");

                    b.Property<string>("MiddleNameGen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Отчество в родительном падеже");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasComment("Идентификатор пользователя (string), последним изменившего запись");

                    b.Property<long>("PersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Идентификатор сотрудника АИС Личное дело");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PersonalId"));

                    b.Property<string>("PersonalNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Личный номер");

                    b.Property<long>("PersonalSubdivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Уникальный автоинкрементный идентификатор подразделения сотрудника в АИС Личное дело");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PersonalSubdivisionId"));

                    b.Property<int?>("PersonnelCategoryCode")
                        .HasColumnType("integer");

                    b.Property<int?>("PersonnelCategoryType")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionCode")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionType")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialRankCode")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialRankType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Текущий статус жизненного цикла записи.");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubdivisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата последнего обновления информации");

                    b.Property<int?>("WorkerCategoryCode")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkerCategoryType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Personals_PersonalId");

                    b.HasIndex("PersonalSubdivisionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Subdivisions_PersonalSubdivisionId");

                    b.HasIndex("SubdivisionId");

                    b.HasIndex("PersonnelCategoryType", "PersonnelCategoryCode");

                    b.HasIndex("PositionType", "PositionCode");

                    b.HasIndex("SpecialRankType", "SpecialRankCode");

                    b.HasIndex("StatusType", "StatusCode");

                    b.HasIndex("WorkerCategoryType", "WorkerCategoryCode");

                    b.ToTable("Personals", null, t =>
                        {
                            t.HasComment("Справочник персонала системы Guard.");
                        });
                });

            modelBuilder.Entity("Guard.Core.Entities.Subdivision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Уникальный идентификатор записи (UUIDv7)");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Адрес");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasComment("Идентификатор пользователя (string), создавшего запись. Ссылается на AspNetUsers.Id");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Факс");

                    b.Property<DateTime>("InsertedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'")
                        .HasComment("Дата и время создания записи (UTC)");

                    b.Property<bool>("IsDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Признак: является ли подразделение отделом");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время последнего изменения записи (UTC)");

                    b.Property<int>("LevelOrder")
                        .HasColumnType("integer")
                        .HasComment("Порядковый номер внутри одного уровня иерархии");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasComment("Идентификатор пользователя (string), последним изменившего запись");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Полное наименование подразделения");

                    b.Property<int?>("OrganTypeCode")
                        .HasColumnType("integer");

                    b.Property<int?>("OrganTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<long>("ParentSubdivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Уникальный автоинкрементный идентификатор родителя");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ParentSubdivisionId"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Путь подразделения");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Телефон");

                    b.Property<string>("PositionFormationName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Наименование для формирования должности");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Почтовый индекс");

                    b.Property<int>("StaffCount")
                        .HasColumnType("integer")
                        .HasComment("Снимок штатной численности (может устаревать)");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Текущий статус жизненного цикла записи.");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusType")
                        .HasColumnType("integer");

                    b.Property<long>("SubdivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Уникальный автоинкрементный идентификатор для Path");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SubdivisionId"));

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата последнего обновления информации");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ParentSubdivisionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Subdivisions_ParentSubdivisionId");

                    b.HasIndex("Path");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Path"), new[] { "varchar_pattern_ops" });

                    b.HasIndex("SubdivisionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Subdivisions_SubdivisionId");

                    b.HasIndex("OrganTypeId", "OrganTypeCode");

                    b.HasIndex("Status", "InsertedDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Subdivisions_Status_InsertedDate");

                    b.HasIndex("StatusType", "StatusCode");

                    b.ToTable("Subdivisions", null, t =>
                        {
                            t.HasComment("Иерархический справочник подразделений организационной структуры системы Guard.");
                        });
                });

            modelBuilder.Entity("Guard.Core.Entities.UserIpAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("IpAddressId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IpAddressId");

                    b.HasIndex("UserId", "IpAddressId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("UserIpAddresses", null, t =>
                        {
                            t.HasComment("Join-таблица связи многие-ко-многим между пользователями и IP-адресами. Хранит метаданные назначения (кто, когда, с какой целью назначил IP).");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Guard.Core.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Guard.Core.Entities.Personal", "Personal")
                        .WithOne("User")
                        .HasForeignKey("Guard.Core.Entities.ApplicationUser", "PersonalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Guard.Core.Entities.OrganType", b =>
                {
                    b.HasOne("Guard.Core.Entities.Classifier", "Classifier")
                        .WithMany()
                        .HasForeignKey("ClassifierType", "Code")
                        .HasPrincipalKey("Type", "Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classifier");
                });

            modelBuilder.Entity("Guard.Core.Entities.Personal", b =>
                {
                    b.HasOne("Guard.Core.Entities.Subdivision", "Subdivision")
                        .WithMany("Personals")
                        .HasForeignKey("SubdivisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Guard.Core.Entities.Classifier", "PersonnelCategory")
                        .WithMany()
                        .HasForeignKey("PersonnelCategoryType", "PersonnelCategoryCode")
                        .HasPrincipalKey("Type", "Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Guard.Core.Entities.Classifier", "Position")
                        .WithMany()
                        .HasForeignKey("PositionType", "PositionCode")
                        .HasPrincipalKey("Type", "Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Guard.Core.Entities.Classifier", "SpecialRank")
                        .WithMany()
                        .HasForeignKey("SpecialRankType", "SpecialRankCode")
                        .HasPrincipalKey("Type", "Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Guard.Core.Entities.Classifier", "StatusClassifier")
                        .WithMany()
                        .HasForeignKey("StatusType", "StatusCode")
                        .HasPrincipalKey("Type", "Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Guard.Core.Entities.Classifier", "WorkerCategory")
                        .WithMany()
                        .HasForeignKey("WorkerCategoryType", "WorkerCategoryCode")
                        .HasPrincipalKey("Type", "Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PersonnelCategory");

                    b.Navigation("Position");

                    b.Navigation("SpecialRank");

                    b.Navigation("StatusClassifier");

                    b.Navigation("Subdivision");

                    b.Navigation("WorkerCategory");
                });

            modelBuilder.Entity("Guard.Core.Entities.Subdivision", b =>
                {
                    b.HasOne("Guard.Core.Entities.Subdivision", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Guard.Core.Entities.OrganType", "OrganType")
                        .WithMany("Subdivisions")
                        .HasForeignKey("OrganTypeId", "OrganTypeCode")
                        .HasPrincipalKey("Id", "Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Guard.Core.Entities.Classifier", "StatusClassifier")
                        .WithMany("Subdivisions")
                        .HasForeignKey("StatusType", "StatusCode")
                        .HasPrincipalKey("Type", "Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrganType");

                    b.Navigation("Parent");

                    b.Navigation("StatusClassifier");
                });

            modelBuilder.Entity("Guard.Core.Entities.UserIpAddress", b =>
                {
                    b.HasOne("Guard.Core.Entities.IpAddress", "IpAddress")
                        .WithMany("UserAssignments")
                        .HasForeignKey("IpAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Guard.Core.Entities.ApplicationUser", "User")
                        .WithMany("UserIpAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IpAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Guard.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Guard.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Guard.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Guard.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Guard.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Guard.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Guard.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("UserIpAddresses");
                });

            modelBuilder.Entity("Guard.Core.Entities.Classifier", b =>
                {
                    b.Navigation("Subdivisions");
                });

            modelBuilder.Entity("Guard.Core.Entities.IpAddress", b =>
                {
                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("Guard.Core.Entities.OrganType", b =>
                {
                    b.Navigation("Subdivisions");
                });

            modelBuilder.Entity("Guard.Core.Entities.Personal", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Guard.Core.Entities.Subdivision", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Personals");
                });
#pragma warning restore 612, 618
        }
    }
}
